name: Test Plugin for Zotero

on:
    workflow_call:
        inputs:
            node-version:
                type: string
                description: 'Node.js version'
                required: false
                default: "20"
            init-cmd:
                type: string
                description: 'Command to initialize the repository'
                required: false
                default: "npm install"
            test-cmd:
                type: string
                description: 'Command to run tests'
                required: false
                default: "npm test"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ github.event.inputs.node-version }}

      - name: Install xvfb # Required for running headless tests
        if: env.ACT != 'true'
        run: sudo apt update && sudo apt install -y xvfb

      - name: Clone Zotero Plugin Scaffold # TEMP: Use the official repository once the PR is merged
        run: |
          git clone --branch add-test https://github.com/windingwind/zotero-plugin-scaffold.git zotero-plugin-scaffold
          cd zotero-plugin-scaffold
          npm install
          npm run build

      - name: Download and Extract Zotero Beta
        run: |
          wget -O zotero.tar.bz2 "https://www.zotero.org/download/client/dl?platform=linux-x86_64&channel=beta"
          tar -xvf zotero.tar.bz2
          echo "Zotero extracted successfully"

      - name: Set Environment Variable for Zotero Bin Path
        run: echo "ZOTERO_PLUGIN_ZOTERO_BIN_PATH=$PWD/Zotero_linux-x86_64/zotero" >> $GITHUB_ENV

      - name: Initialize Current Repository
        run: |
            ${{ github.event.inputs.init-cmd }}

      - name: Install Zotero Plugin Scaffold Locally # TEMP: Use the official repository once the PR is merged
        run: |
          npm install ./zotero-plugin-scaffold

      - name: Run Tests
        run: |
          xvfb-run ${{ github.event.inputs.test-cmd }}
        env:
          ZOTERO_PLUGIN_ZOTERO_BIN_PATH: ${{ env.ZOTERO_PLUGIN_ZOTERO_BIN_PATH }}
